export default [
    {
        id: "rci9bQHKtBc",
        release: new Date("Feb 7, 2026"),
        creator: "Mysda",
        title: "How to make a Tunnel Builder for your Trains?",
        tags: [],
    },
    {
        id: "KO__nxaK0VM",
        release: new Date("Aug 22, 2025"),
        creator: "Mysda",
        title: "How to make a perfect STORAGE SYSTEM?",
        tags: [],
    },
    {
        id: "-q6-gvweWgk",
        release: new Date("Aug 21, 2025"),
        creator: "UncleRanger",
        title: "I Built the ULTIMATE Factory!",
        tags: [],
    },
    {
        id: "z4XX6GPufGw",
        release: new Date("Aug 7, 2025"),
        creator: "UncleRanger",
        title: "INFINITE ENERGY From Just 9 Lava Buckets!",
        tags: [],
    },
    {
        id: "hZhPjUdq4Jw",
        release: new Date("Jul 31, 2025"),
        creator: "UncleRanger",
        title: "I Built an INSTANT Crushing Setup!",
        tags: [],
    },
    {
        id: "pq698_SONjk",
        release: new Date("Jul 13, 2025"),
        creator: "UncleRanger",
        title: "32000 SU Steam Power WITHOUT Blaze Burners?",
        tags: [],
    },
    {
        id: "fuCaBo4Xetc",
        release: new Date("Jun 30, 2025"),
        creator: "UncleRanger",
        title: "Mining with the Create Mod WITHOUT Drills?",
        tags: [],
    },
]