$schema: "https://moonrepo.dev/schemas/tasks.json"

implicitInputs:
  - "assets/**/*"
  - "assets/*"
  - "source/**/*"
  - "source/*"

tasks:
  fmt:
    extends: "exec"
    args: deno fmt
  install:
    inputs: [ "deno.json", "deno.lock" ]
    extends: "exec"
    args: deno install
  dev:
    extends: "exec"
    args: deno task dev
    local: true
  build:
    extends: "exec"
    args: deno task build
  preview:
    extends: "exec"
    args: deno task preview
  deploy:
    extends: "exec"
    args: deno task deploy
